### ISSUE TITLE
Error: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by neumartin** [manijak/nativescript-photoviewer#31]
Hi!

I have this error when executing in Android emulator:

```
System.err: com.tns.NativeScriptException: 

System.err: Calling js method run failed

System.err: 

System.err: Error: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

System.err:     android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1434)

System.err:     android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1452)

System.err:     android.app.BackStackRecord.commitInternal(BackStackRecord.java:708)

System.err:     android.app.BackStackRecord.commit(BackStackRecord.java:672)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:983)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:967)

System.err:     com.tns.Runtime.callJSMethod(Runtime.java:959)

System.err:     com.tns.gen.java.lang.Runnable.run(Runnable.java:15)

System.err:     android.os.Handler.handleCallback(Handler.java:751)
System.err:     android.os.Handler.dispatchMessage(Handler.java:95)

System.err:     android.os.Looper.loop(Looper.java:154)

System.err:     android.app.ActivityThread.main(ActivityThread.java:6119)
System.err:     java.lang.reflect.Method.invoke(Native Method)

System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)

System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
System.err: File: "file:///data/data/com.autocorp.autocorpapp/files/app/tns_modules/tns-core-modules/ui/frame/frame.js, line: 256, column: 20
System.err: 

System.err: StackTrace: 
System.err: 	Frame: function:'Frame._navigateCore', file:'file:///data/data/com.autocorp.autocorpapp/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 256, column: 21
System.err: 	Frame: function:'FrameBase.performNavigation', file:'file:///data/data/com.autocorp.autocorpapp/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 235, column: 14
System.err: 	Frame: function:'FrameBase._processNextNavigationEntry', file:'file:///data/data/com.autocorp.autocorpapp/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 227, column: 22
System.err: 	Frame: function:'Frame._processNextNavigationEntry', file:'file:///data/data/com.autocorp.autocorpapp/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 138, column: 58
System.err: 	Frame: function:'FrameBase._processNavigationQueue', file:'file:///data/data/com.autocorp.autocorpapp/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 187, column: 14
System.err: 	Frame: function:'Frame.setCurrent', file:'file:///data/data/com.autocorp.autocorpapp/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 206, column: 18
System.err: 	Frame: function:'', file:'file:///data/data/com.autocorp.autocorpapp/files/app/tns_modules/tns-core-modules/ui/frame/fragment.transitions.js', line: 578, column: 53
System.err: 	Frame: function:'invoke', file:'file:///data/data/com.autocorp.autocorpapp/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 19, column: 48
System.err: 	Frame: function:'run', file:'file:///data/data/com.autocorp.autocorpapp/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 23, column: 13
System.err: 
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:983)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err: 	at com.tns.gen.java.lang.Runnable.run(Runnable.java:15)
System.err: 	at android.os.Handler.handleCallback(Handler.java:751)

System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
System.err: 	at android.os.Looper.loop(Looper.java:154)

System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6119)

System.err: 	at java.lang.reflect.Method.invoke(Native Method)

System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)

System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

System.err: Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

System.err: 	at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1434)

System.err: 	at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1452)

System.err: 	at android.app.BackStackRecord.commitInternal(BackStackRecord.java:708)

System.err: 	at android.app.BackStackRecord.commit(BackStackRecord.java:672)

System.err: 	... 14 more
```

**Comment by manijak** [comment]
Please try the new version, demo app tested on api 28 and works fine.
