### ISSUE TITLE
App crashes after updating NS and SDK

### ISSUE THREAD

**Issue by VeeK727** [manijak/nativescript-photoviewer#32]
I recently upgraded to NS 5 and android SDK 28 and since then the app crashes when starting the gallery on android. Here's the error:

```
System.err: java.lang.NoSuchMethodError: No static method with(Landroid/content/Context;)Lcom/squareup/picasso/Picasso; in class Lcom/squareup/picasso/Picasso; or its super classes (declaration of 'com.squareup.picasso.Picasso' appears in /data/app/com.media.bwd.yashornaments-1/base.apk)
System.err: 	at com.etiennelawlor.imagegallery.library.adapters.FullScreenImageGalleryAdapter.instantiateItem(FullScreenImageGalleryAdapter.java:54)
System.err: 	at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1010)
System.err: 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1158)
System.err: 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1092)
System.err: 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1622)
System.err: 	at android.view.View.measure(View.java:19862)
System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6091)
System.err: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err: 	at android.view.View.measure(View.java:19862)
System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6091)
System.err: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err: 	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
System.err: 	at android.view.View.measure(View.java:19862)
System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6091)
System.err: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
System.err: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
System.err: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
System.err: 	at android.view.View.measure(View.java:19862)
System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6091)
System.err: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err: 	at android.view.View.measure(View.java:19862)
System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6091)
System.err: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
System.err: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
System.err: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
System.err: 	at android.view.View.measure(View.java:19862)
System.err: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6091)
System.err: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:724)
System.err: 	at android.view.View.measure(View.java:19862)
System.err: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
System.err: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1366)
System.err: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
System.err: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
System.err: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6350)
System.err: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
System.err: 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
System.err: 	at android.view.Choreographer.doFrame(Choreographer.java:621)
System.err: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
System.err: 	at android.os.Handler.handleCallback(Handler.java:751)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
System.err: 	at android.os.Looper.loop(Looper.java:154)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

Perhaps the module requires changes to work with API 28.  Here's the config

```
 Component nativescript has 5.0.3 version and is up to date.
 Component tns-core-modules has 5.2.0-2018-11-15-221043-02 version and is up to date.
 Component tns-android has 5.0.0 version and is up to date.
 Component tns-ios has 5.0.0 version and is up to date.
```

**Comment by stevenspiel** [comment]
I'm also experiencing this

**Comment by manijak** [comment]
new version has just been published. works fine in tns 5.1.x

**Comment by VeeK727** [comment]
Hey @manijak The problem is still present. Can you confirm? Also the core library is at 0.1.0 while this is using 0.0.13. Can you upgrade the library please?

**Comment by dodongphure** [comment]
Same issue, cheers.

**Comment by VeeK727** [comment]
The problem is actually coming from Fresco which uses Picasso. Picasso has been deprecated and after updating NS, it doesn't work at all. I removed it and now everything works.

**Comment by patrikengborg** [comment]
@VeeK727 I'm having this issue, and can't find a solution.

Can I ask how you did to remove the Picasso dependency?

**Comment by VeeK727** [comment]
Ahh...its been a year. I'm not really sure what I did. I think Fresco was another plugin I had or some other image plugin was using the Fresco library. I removed that.
